### ISSUE TITLE
copies images to MEDIA_ROOT from settings instead of local_settings

### ISSUE THREAD

**Issue by jbwexler** [leetrout/django-fixturemedia#12]
In my app, the settings file imports MEDIA_ROOT from local_settings, so that uploading files will be saved to the MEDIA_ROOT specified in local_settings, not in settings. However, when I run 'python manage.py collectmedia' using django-fixturemedia, the files are copied to the MEDIA_ROOT specified in settings instead of local_settings. Is there a way around this?

**Comment by leetrout** [comment]
As long as you are following normal settings import conventions it will work as desired...

in `setttings.py`:

``` python
# All of your settings here
# At the bottom
from local_settings.py import *
```

Otherwise you'll have to explicitly declare the settings module in `DJANGO_SETTINGS_MODULE` or use the manage.py flag `--settings` https://docs.djangoproject.com/en/1.7/ref/django-admin/#django-admin-option---settings

**Comment by jbwexler** [comment]
Thanks for getting back to me. Turned out I was making a silly error. Works fine now.

**Comment by leetrout** [comment]
:+1:
